CheckBoxTest/Models/Items.cs
namespace CheckBoxTest.Models
{
    public class Items
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
    }
}

CheckBoxTest/Models/ItemsIndexVM.cs
using System.Collections.Generic;

namespace CheckBoxTest.Models
{
    public class ItemsIndexVM
    {
        public List<Items> AllItems { get; set; }
        public string TestWord { get; set; }
    }
}

CheckBoxTest/Models/ToggleDTO.cs
namespace CheckBoxTest.Models
{
    public class ToggleDTO
    {
        public int Id { get; set; }
        public bool Status { get; set; }
    }
}

CheckBoxTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CheckBoxTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CheckBoxTest/Controllers/ItemsController.cs
using CheckBoxTest.Data;
using CheckBoxTest.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CheckBoxTest.Controllers
{
    public class ItemsController : Controller
    {
        private CheckBoxTestContext db = new CheckBoxTestContext();

        // GET: Items
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }


        public ActionResult Index2()
        {
            var allItems = db.Items.ToList();
            var model = new ItemsIndexVM
            {
                AllItems = allItems,
                TestWord = "OH, HALLO!"

            };

            return View(model);
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Status")] Items items)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(items);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(items);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Status")] Items items)
        {
            if (ModelState.IsValid)
            {
                db.Entry(items).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(items);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Items items = db.Items.Find(id);
            if (items == null)
            {
                return HttpNotFound();
            }
            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Items items = db.Items.Find(id);
            db.Items.Remove(items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //[AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult RegisterToggle(int? id)
        {
            var item = db.Items.Find(id);

            //if (!item.Status)
            //{
            //    item.Status = false;

            //}
            //else
            //{
            //    item.Status = true;
            //}

            item.Status = item.Status ? false : true;

            db.Entry(item).State = EntityState.Modified;
            db.SaveChanges();


            return Content("Status toggled");
        }

        [HttpPost]
        public ActionResult RegisterToggle2(IEnumerable<ToggleDTO> items)
        {


            foreach (var item in items)
            {
                var itemToChange = db.Items.Find(item.Id);
                itemToChange.Status = item.Status ? true : false;
                db.Entry(itemToChange).State = EntityState.Modified;
            }

            db.SaveChanges();



            return Content("Status toggled");
        }


        [HttpPost]
        public ActionResult TakeItems(ItemsIndexVM model)
        {
            return View(nameof(Index2));
        }

    }
}

CheckBoxTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CheckBoxTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CheckBoxTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CheckBoxTest/Views/Items/Create.cshtml
@model CheckBoxTest.Models.Items

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CheckBoxTest/Views/Items/Delete.cshtml
@model CheckBoxTest.Models.Items

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CheckBoxTest/Views/Items/Details.cshtml
@model CheckBoxTest.Models.Items

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CheckBoxTest/Views/Items/Edit.cshtml
@model CheckBoxTest.Models.Items

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CheckBoxTest/Views/Items/Index.cshtml
@model IEnumerable<CheckBoxTest.Models.Items>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="hobbittable" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Status)*@
                @if (item.Status)
                {
                    <input id="@item.Id" type="checkbox" value="@item.Id" checked/>
                }
                else
                {
                    <input id="@item.Id" type="checkbox" value="@item.Id" />
                }
                

            </td>
        </tr>
    }

</table>

<input type="button" id="toggleButton" value="Save" />
<input type="checkbox" id="masterCheck" value="Check/Uncheck All" />


@section Scripts{
    @*@Scripts.Render("~/bundles/jqueryunobtrusive")*@


    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script type="text/javascript">

        document.querySelector('#toggleButton').addEventListener('click', toggle);
        document.querySelector('#masterCheck').addEventListener('click', checkAll);

        function checkAll() {
            var masterCheck = document.getElementById("masterCheck");
            var itemIdsAndStatus = document.querySelectorAll('td:nth-child(2)');

            for (var i = 0; i < itemIdsAndStatus.length; i++) {      

                if (masterCheck.checked) {
                    itemIdsAndStatus[i].children[0].checked = true;
                }
                else
                {
                    itemIdsAndStatus[i].children[0].checked = false;
                }
                
            }

        }

        function toggle() {

            var itemIdsAndStatus = document.querySelectorAll('td:nth-child(2)');
            var postData = [];


            for (var i = 0; i < itemIdsAndStatus.length; i++) {
                var jsonData = {};
                jsonData["id"] = itemIdsAndStatus[i].children[0].id;
                jsonData["status"] = itemIdsAndStatus[i].children[0].checked
                postData.push(jsonData);

            }
            console.log(postData);
            
            $.ajax({
                type: "POST",
                url: `/Items/RegisterToggle2/`,
                contentType: "application/json",
                data: JSON.stringify(postData),
                success: function (r) {
                    if (r) {
                        alert("Success");
                    } else {
                        alert("Failure");
                    }
                }
            });
        }
    </script>


}

CheckBoxTest/Views/Items/Index2.cshtml
@model CheckBoxTest.Models.ItemsIndexVM


@{
    ViewBag.Title = "Index2";
}

<h2>Index2</h2>

<table>
    @foreach (var item in Model.AllItems)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
    }
</table>



@using (Html.BeginForm("TakeItems", "Items", new { FormMethod.Post } ))
{



        @*@Html.HiddenFor(model => model.AllItems)*@

        @Html.HiddenFor(m => m.TestWord);

        for (int i = 0; i < Model.AllItems.Count; i++)
        {
            <div class="form-group">
                @Html.HiddenFor(m => m.AllItems[i].Id)
                @Html.HiddenFor(m => m.AllItems[i].Name)
                @Html.HiddenFor(m => m.AllItems[i].Status)
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    
}

CheckBoxTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Items", "Index", "Items")</li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Items2", "Index2", "Items")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>